### PR TITLE
US749035/US857114: Move to Worker Framework 8

### PR DESCRIPTION
**Pull request by jonny-mccoubrey**
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=857114

### CODE REVIEW

**Review by dermot-hardy — COMMENTED** [review]
Do these changes break compatibility with Worker Framework 7?

**Comment by jonny-mccoubrey** [comment]
> Do these changes break compatibility with Worker Framework 7?



> Do these changes break compatibility with Worker Framework 7?

Yes, I believe so.

**Comment by dermot-hardy** [comment]
Then it can't be merged or you'll break everything that's currently using WF7.  Raise a release ticket for this component and get v2.0.0 of it released, including all the downstreams.  After that this can be merged as a new breaking change, moving this to 3.0.0-SNAPSHOT.

**Comment by jonny-mccoubrey** [comment]
> Then it can't be merged or you'll break everything that's currently using WF7. Raise a release ticket for this component and get v2.0.0 of it released, including all the downstreams. After that this can be merged as a new breaking change, moving this to 3.0.0-SNAPSHOT.

@dermot-hardy worker-framework-testing v2.0.0 has now been released as support for services on Worker Framework 7

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
